"""rename department

Revision ID: 6cb60b1d9026
Revises: 7786c4bdec4d
Create Date: 2025-11-03 14:54:50.950390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb60b1d9026'
down_revision = '7786c4bdec4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###
